import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Error.module.scss";
import HomePage from "@/components/home";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ apiData }) {
  console.log(apiData)
  return (
    <>
      <Head>
        <title>Shade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage language="en" />
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("https://pokeapi.co/api/v2/");
  const apiData = await res.json();

  return { props: { apiData } };
}