import createContent from "@/common/CreateContent";
import Services from "@/components/services/Services";
import { backendAPI } from "@/contexts/GlobalContext";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Service({ apiData }) {
  const [isLoading, setIsLoading] = useState(true);
  const [content, setContent] = useState(null);

  useEffect(() => {
    if (apiData && Object.keys(apiData).length > 0 && apiData.content) {
      const generatedContent = createContent(apiData.content);
      setContent(generatedContent.content);
      setIsLoading(false);
    } else {
      // keep loading forever or retry (optional)
      console.warn("API response is empty. Keeping loader active...");
    }
  }, [apiData]);

  // if (isLoading) {
  //   return <Loader />;
  // }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Services content={content} />
    </>
  );
}

export async function getServerSideProps() {
  try {
    const res = await fetch(`${backendAPI}service`);

    if (!res.ok) {
      // If response failed (e.g., 404, 500), return empty object
      return { props: { apiData: {} } };
    }

    const apiData = await res.json();

    return { props: { apiData: apiData || {} } };
  } catch (error) {
    // If fetch throws an error (e.g., network failure), return empty object
    return { props: { apiData: {} } };
  }
}