import Head from "next/head";
import SolutionPage from "@/components/solution/Solution";

export default function Solution() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SolutionPage />
    </>
  );
}
