import NewsBlogDetailPage from "@/components/news-and-blogs/NewsBlogDetailPage";
import Head from "next/head";

// export async function getStaticPaths() {
//     const paths = industry.map(detail => ({
//         params: { id: detail.id }
//     }));

//     return {
//         paths,
//         fallback: false // can also be true or 'blocking'
//     };
// }

// export async function getStaticProps({ params }) {
//     const detail = industry.find(p => p.id === params.id);

//     // If the project is not found, return a 404 page
//     if (!detail) {
//         return {
//             notFound: true,
//         };
//     }

//     return {
//         props: { detail },
//     };
// }

export default function NewsAndBlogsDetail({ detail }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NewsBlogDetailPage />
        </>
    );
}
